/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application.telas;

import Application.validacao.ValidacaoSenha;

import java.awt.event.KeyEvent;

/**
 *
 * @author 825158824
 */
public class CadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTela
     */
    public CadastroTela() {
        super ("Cadastro de Usuário");
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLoginCadastro = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JTextField();
        btnConfirmarCadastro = new javax.swing.JButton();
        btnVoltarCadastro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLoginCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Login:"));
        txtLoginCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginCadastroActionPerformed(evt);
            }
        });
        txtLoginCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginCadastroKeyPressed(evt);
            }
        });

        senhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha:"));
        senhaPasswordField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                senhaPasswordFieldPropertyChange(evt);
            }
        });
        senhaPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaPasswordFieldKeyPressed(evt);
            }
        });

        btnConfirmarCadastro.setText("Confirmar");
        btnConfirmarCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnConfirmarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCadastroActionPerformed(evt);
            }
        });
        btnConfirmarCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarCadastroKeyPressed(evt);
            }
        });

        btnVoltarCadastro.setText("Voltar");
        btnVoltarCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVoltarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCadastroActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("O login deve conter:\n- Seu nome, dia e mês de nascimento\nEx: (nome0102)\nA senha deve conter:\n- De 8 a 32 caracteres\n- Letras maiúsculas e minúsculas\n- pelo menos um número");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltarCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmarCadastro)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(senhaPasswordField)
                            .addComponent(txtLoginCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtLoginCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarCadastro)
                    .addComponent(btnConfirmarCadastro))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCadastroActionPerformed
        LoginTela t = new LoginTela();
        t.setVisible(true);
        this.dispose(); //sai
    }//GEN-LAST:event_btnVoltarCadastroActionPerformed

    private void btnConfirmarCadastroActionPerformed(java.awt.event.ActionEvent evt) {
        String senha = senhaPasswordField.getText();
        String login = txtLoginCadastro.getText();
        boolean validacao = ValidacaoSenha.validacao(senha, login);
        if(ValidacaoSenha.cadastro(login, senha, validacao)){
            LoginTela t = new LoginTela();
            t.setVisible(true);
            this.dispose(); //sai
        }
    }

    private void txtLoginCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginCadastroActionPerformed

    private void txtLoginCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginCadastroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          senhaPasswordField.requestFocus();  
        }
    }//GEN-LAST:event_txtLoginCadastroKeyPressed

    private void senhaPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaPasswordFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          btnConfirmarCadastro.requestFocus();  
        }
    }//GEN-LAST:event_senhaPasswordFieldKeyPressed

    private void btnConfirmarCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmarCadastroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String senha = senhaPasswordField.getText();
            String login = txtLoginCadastro.getText();
            boolean validacao = ValidacaoSenha.validacao(senha, login);
            if(ValidacaoSenha.cadastro(login, senha, validacao)){
                LoginTela t = new LoginTela();
                t.setVisible(true);
                this.dispose(); //sai
            }
        }
    }//GEN-LAST:event_btnConfirmarCadastroKeyPressed

    private void senhaPasswordFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_senhaPasswordFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarCadastro;
    private javax.swing.JButton btnVoltarCadastro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField senhaPasswordField;
    private javax.swing.JTextField txtLoginCadastro;
    // End of variables declaration//GEN-END:variables
}
