
package Application.telas;

import Application.api.ApiCEP;
import Application.dto.EnderecoDto;
import Application.validacao.ValidacaoInserir;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.io.IOException;

public class InserirTela extends javax.swing.JFrame {

    public InserirTela() {
        super ("Inserir Pessoa");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    //CRIAÇÃO DOS OBJETO DA API
    //ApiCEP apiCEP = new ApiCEP();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeInserir = new javax.swing.JTextField();
        txtCpfInserir = new javax.swing.JTextField();
        txtTelefoneInserir = new javax.swing.JTextField();
        txtCepInserir = new javax.swing.JTextField();
        btnConfirmarInserir = new javax.swing.JButton();
        btnVoltarInserir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNecessidadesInserir = new javax.swing.JTextArea();
        txtCidadeInserir = new javax.swing.JTextField();
        txtBairroInserir = new javax.swing.JTextField();
        txtNumInserir = new javax.swing.JTextField();
        txtUFInserir = new javax.swing.JTextField();
        txtComplementoInserir = new javax.swing.JTextField();
        txtRuaInserir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir Pessoa:"));

        txtNomeInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome:"));
        txtNomeInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeInserirKeyPressed(evt);
            }
        });

        txtCpfInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF:"));
        txtCpfInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfInserirKeyPressed(evt);
            }
        });

        txtTelefoneInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone:"));
        txtTelefoneInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneInserirActionPerformed(evt);
            }
        });
        txtTelefoneInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneInserirKeyPressed(evt);
            }
        });

        txtCepInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("CEP:"));
        txtCepInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepInserirActionPerformed(evt);
            }
        });
        txtCepInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCepInserirKeyPressed(evt);
            }
        });

        btnConfirmarInserir.setText("Confirmar");
        btnConfirmarInserir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnConfirmarInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarInserirActionPerformed(evt);
            }
        });

        btnVoltarInserir.setText("Voltar");
        btnVoltarInserir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVoltarInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltarInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarInserirActionPerformed(evt);
            }
        });

        txtNecessidadesInserir.setColumns(20);
        txtNecessidadesInserir.setRows(5);
        txtNecessidadesInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Necessidades:"));
        txtNecessidadesInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNecessidadesInserirKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtNecessidadesInserir);

        txtCidadeInserir.setEditable(false);
        txtCidadeInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Cidade:"));
        txtCidadeInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCidadeInserirKeyPressed(evt);
            }
        });

        txtBairroInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Bairro:"));
        txtBairroInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroInserirKeyPressed(evt);
            }
        });

        txtNumInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Número:"));
        txtNumInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumInserirActionPerformed(evt);
            }
        });
        txtNumInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumInserirKeyPressed(evt);
            }
        });

        txtUFInserir.setEditable(false);
        txtUFInserir.setActionCommand("<Not Set>");
        txtUFInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("UF:"));
        txtUFInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUFInserirKeyPressed(evt);
            }
        });

        txtComplementoInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Complemento (não obrigatório):"));
        txtComplementoInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComplementoInserirKeyPressed(evt);
            }
        });

        txtRuaInserir.setBorder(javax.swing.BorderFactory.createTitledBorder("Rua:"));
        txtRuaInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRuaInserirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCpfInserir)
                    .addComponent(txtNomeInserir)
                    .addComponent(txtTelefoneInserir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCepInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidadeInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtRuaInserir, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUFInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtComplementoInserir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(txtBairroInserir, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirmarInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltarInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNomeInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpfInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefoneInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidadeInserir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCepInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtUFInserir))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumInserir)
                            .addComponent(txtRuaInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairroInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmarInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltarInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(txtComplementoInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarInserirActionPerformed
        //retorna a tela de CRUD
        CRUDTela t = new CRUDTela();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarInserirActionPerformed

    private void btnConfirmarInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarInserirActionPerformed
        //coletar o q foi digitado
        String nome = txtNomeInserir.getText();
        String cpf = txtCpfInserir.getText();
        String telefone = txtTelefoneInserir.getText();
        String endereco = "CEP: " + txtCepInserir.getText() + "\nCidade: " + txtCidadeInserir.getText() + "\nUF: " + txtUFInserir.getText() + "\nEndereço: " + txtRuaInserir.getText() + ", " + txtNumInserir.getText() + ", " + txtBairroInserir.getText() + "\n" + txtComplementoInserir.getText();
        String necessidades = txtNecessidadesInserir.getText();

        if(!txtCepInserir.getText().isEmpty()){
            if(ValidacaoInserir.validarInserir(nome, cpf, telefone, endereco, necessidades)){
                CRUDTela t = new CRUDTela();
                t.setVisible(true);
                this.dispose();
            }
        }else {
            JOptionPane.showMessageDialog(null, "Insira um CEP válido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarInserirActionPerformed

    private void txtTelefoneInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneInserirActionPerformed

    private void txtNomeInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          txtCpfInserir.requestFocus();  
        }
    }//GEN-LAST:event_txtNomeInserirKeyPressed

    private void txtCpfInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          txtTelefoneInserir.requestFocus();  
        }
    }//GEN-LAST:event_txtCpfInserirKeyPressed

    private void txtTelefoneInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          txtCepInserir.requestFocus();  
        }
    }//GEN-LAST:event_txtTelefoneInserirKeyPressed

    private void txtCepInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          txtRuaInserir.requestFocus();  
        }
    }//GEN-LAST:event_txtCepInserirKeyPressed

    private void txtNecessidadesInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNecessidadesInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String texto = txtNecessidadesInserir.getText();
            txtNecessidadesInserir.setText(texto + "; ");
        }
    }//GEN-LAST:event_txtNecessidadesInserirKeyPressed

    private void txtCidadeInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeInserirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeInserirKeyPressed

    private void txtBairroInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){txtComplementoInserir.requestFocus();
        }
    }//GEN-LAST:event_txtBairroInserirKeyPressed

    private void txtNumInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          txtBairroInserir.requestFocus();  
        }
    }//GEN-LAST:event_txtNumInserirKeyPressed

    private void txtUFInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUFInserirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUFInserirKeyPressed

    private void txtComplementoInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          txtNecessidadesInserir.requestFocus();  
        }
    }//GEN-LAST:event_txtComplementoInserirKeyPressed

    private void txtNumInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumInserirActionPerformed
        
    }//GEN-LAST:event_txtNumInserirActionPerformed

    private void txtRuaInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaInserirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          txtNumInserir.requestFocus();  
        }
    }//GEN-LAST:event_txtRuaInserirKeyPressed

    private void txtCepInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepInserirActionPerformed
        //AQUI VAI TER A API PEGANDO O DADO DE CEP COLOCADO E SETANDO OS OUTROS TEXTOS:
        try{
            ApiCEP apiCEP = new ApiCEP();
            EnderecoDto enderecoDto = apiCEP.getEndereco(txtCepInserir.getText());
            txtCidadeInserir.setText(enderecoDto.getLocalidade());
            txtUFInserir.setText(enderecoDto.getUf());
        } catch (IOException | InterruptedException e){ //collapse
            JOptionPane.showMessageDialog(null, "Erro, verifique o CEP digitado.", "Atenção!", JOptionPane.ERROR_MESSAGE);
            throw new RuntimeException(e);
        }

    }//GEN-LAST:event_txtCepInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarInserir;
    private javax.swing.JButton btnVoltarInserir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBairroInserir;
    private javax.swing.JTextField txtCepInserir;
    private javax.swing.JTextField txtCidadeInserir;
    private javax.swing.JTextField txtComplementoInserir;
    private javax.swing.JTextField txtCpfInserir;
    private javax.swing.JTextArea txtNecessidadesInserir;
    private javax.swing.JTextField txtNomeInserir;
    private javax.swing.JTextField txtNumInserir;
    private javax.swing.JTextField txtRuaInserir;
    private javax.swing.JTextField txtTelefoneInserir;
    private javax.swing.JTextField txtUFInserir;
    // End of variables declaration//GEN-END:variables
}
