
package Aplication.telas;

import java.awt.event.KeyEvent;

/**
 *
 * @author 825158824
 */
public class ExcluirTela extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirTela
     */
    public ExcluirTela() {
        super ("Excluir pessoa");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void confirmar(){
        int id = Integer.parseInt(txtIdExcluir.getText());
        Confirmacao confirmacao = new Confirmacao();
        confirmacao.popUpCadastro(id);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdExcluir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConfirmarExcluir = new javax.swing.JButton();
        btnVoltarExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdExcluir.setBorder(javax.swing.BorderFactory.createTitledBorder("Id:"));
        txtIdExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdExcluirActionPerformed(evt);
            }
        });
        txtIdExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdExcluirKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ATENÇÃO! Tenha certeza de que o usuário digitado é o que deseja que seja excluido");

        btnConfirmarExcluir.setText("Confirmar");
        btnConfirmarExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnConfirmarExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarExcluirActionPerformed(evt);
            }
        });
        btnConfirmarExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarExcluirKeyPressed(evt);
            }
        });

        btnVoltarExcluir.setText("Voltar");
        btnVoltarExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVoltarExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnConfirmarExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnVoltarExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfirmarExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnVoltarExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdExcluirActionPerformed

    private void btnConfirmarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarExcluirActionPerformed
        confirmar();
    }//GEN-LAST:event_btnConfirmarExcluirActionPerformed

    private void btnVoltarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarExcluirActionPerformed
        CRUDTela t = new CRUDTela();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarExcluirActionPerformed

    private void txtIdExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdExcluirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          btnConfirmarExcluir.requestFocus();  
        }
    }//GEN-LAST:event_txtIdExcluirKeyPressed

    private void btnConfirmarExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmarExcluirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          confirmar();  
        }
    }//GEN-LAST:event_btnConfirmarExcluirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarExcluir;
    private javax.swing.JButton btnVoltarExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIdExcluir;
    // End of variables declaration//GEN-END:variables
}
